[versions]
jweust = "INTERNAL"
kotlin = "1.8.20"
compose = "1.4.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jweust = { id = "me.heizi.jweust", version.ref = "jweust" }