/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.heizi.jweust

import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.Test

/**
 * A simple functional test for the 'me.heizi.jweust.greeting' plugin.
 */
class JweustPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle.kts") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle.kts") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id("me.heizi.jweust")
                `java`
            }
            group = "me.heizi.jweust"
            version = "1.0"
            jweust {
                defaults()
                includeJarByGenerate()
            }
        """.trimIndent())


        // Run the build
        GradleRunner.create().
        withPluginClasspath().
        withArguments("jar","jweust","--stacktrace","--info",).
        withProjectDir(projectDir).
        forwardOutput().
        build()
//

//        // Verify the result
//        assertTrue(result.output.contains("Hello from plugin 'me.heizi.jweust.greeting'"))
    }
}
